import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, test } from "node:test";
import { CODES } from "../cli/codes.ts";
import { run, type Io } from "../cli/main.ts";
import { VERSION } from "../cli/version.ts";
import { ROOT } from "./helpers.ts";

const temp = mkdtempSync(join(tmpdir(), "prism-cli-"));
after(() => rmSync(temp, { recursive: true, force: true }));

function cli(...argv: string[]): { code: number; out: string; err: string } {
  const out: string[] = [];
  const err: string[] = [];
  const io: Io = { cwd: temp, out: (t) => out.push(t), err: (t) => err.push(t) };
  const code = run(argv, io);
  return { code, out: out.join("\n"), err: err.join("\n") };
}

const schema = readFileSync(join(ROOT, "examples/quickstart/save.prism"), "utf8");

test("the CLI version matches package.json", () => {
  const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as { version: string };
  assert.equal(VERSION, pkg.version);
  assert.equal(cli("--version").out, VERSION);
});

test("init installs the runtime, prints the modules line and refuses to overwrite local edits", () => {
  const first = cli("init", "Lib/Prism");
  assert.equal(first.code, 0);
  assert.match(first.out, /Prism<public> := module:/);
  assert.ok(existsSync(join(temp, "Lib/Prism/prism_runner.verse")));
  writeFileSync(join(temp, "Lib/Prism/prism_util.verse"), "# edited\n");
  assert.equal(cli("init", "Lib/Prism").code, 1);
  assert.equal(cli("init", "Lib/Prism", "--sync").code, 0);
  assert.notEqual(readFileSync(join(temp, "Lib/Prism/prism_util.verse"), "utf8"), "# edited\n");
});

test("generate finds the runtime, writes once, then reports up to date", () => {
  writeFileSync(join(temp, "save.prism"), schema);
  const first = cli("generate", "save.prism");
  assert.equal(first.code, 0, first.err);
  const store = readFileSync(join(temp, "player_save_store.verse"), "utf8");
  assert.match(store, /using \{ Lib\.Prism \}/);
  assert.match(store, /^# Code generated by prism-verse .* \(sha256:[0-9a-f]{16}\)\. DO NOT EDIT\.$/m);
  assert.match(cli("generate", "save.prism").out, /up to date/);
});

test("generate --check fails when the generated files are stale, without writing", () => {
  assert.equal(cli("generate", "save.prism", "--check").code, 0);
  writeFileSync(join(temp, "save.prism"), schema.replace("@max(100)", "@max(99)"));
  const stale = cli("generate", "save.prism", "--check");
  assert.equal(stale.code, 1);
  assert.match(stale.err, /out of date/);
  assert.doesNotMatch(readFileSync(join(temp, "player_save_model.verse"), "utf8"), /99/);
  writeFileSync(join(temp, "save.prism"), schema);
});

test("names prints the saved name of every field; names.json is the source of truth", () => {
  const names = cli("names", "save.prism");
  assert.equal(names.code, 0, names.err);
  assert.match(names.out, /^PlayerSave \(player_save_record\)$/m);
  assert.match(names.out, /^  Coins +-> {2}[a-z][a-z0-9]?$/m);
  const path = join(temp, "prism/save/names.json");
  const saved = readFileSync(path, "utf8");
  rmSync(path);
  const missing = cli("generate", "save.prism", "--check");
  assert.equal(missing.code, 1);
  assert.match(missing.err, /names\.json is out of date/);
  assert.equal(cli("generate", "save.prism").code, 0);
  assert.equal(readFileSync(path, "utf8"), saved);
  writeFileSync(path, saved.replace(/"Coins": "[a-z0-9]+"/, '"Coins": "zz"'));
  assert.equal(cli("generate", "save.prism").code, 0);
  assert.match(readFileSync(join(temp, "player_save_records.verse"), "utf8"), /^ {4}zz<public>:float = 0\.0$/m);
  writeFileSync(path, "{");
  const unreadable = cli("generate", "save.prism");
  assert.equal(unreadable.code, 1);
  assert.match(unreadable.err, /error\[P109\]/);
  writeFileSync(path, saved);
  assert.equal(cli("generate", "save.prism").code, 0);
});

test("lock records a shape once, then a breaking edit fails with the field and the fix", () => {
  const first = cli("lock", "save.prism");
  assert.equal(first.code, 0, first.err);
  assert.ok(existsSync(join(temp, "prism/save/0001.json")));
  assert.match(cli("lock", "save.prism").out, /unchanged/);
  assert.ok(!existsSync(join(temp, "prism/save/0002.json")));
  writeFileSync(join(temp, "save.prism"), schema.replace("Level       Int   = 1   @min(1)", "Level       Int   = 5   @min(1)"));
  const broken = cli("generate", "save.prism");
  assert.equal(broken.code, 1);
  assert.match(broken.err, /error\[P103\]/);
  assert.match(broken.err, /@initial\(5\)/);
  assert.equal(cli("lock", "save.prism").code, 1);
  writeFileSync(join(temp, "save.prism"), schema);
});

test("--format json and github", () => {
  writeFileSync(join(temp, "bad.prism"), "model A {\n  X Nope\n}\n");
  const json = cli("check", "bad.prism", "--format", "json");
  assert.equal(json.code, 1);
  const parsed = JSON.parse(json.err) as { code: string; line: number; column: number }[];
  assert.deepEqual(parsed.map((d) => [d.code, d.line, d.column]), [["P012", 2, 5]]);
  const github = cli("check", "bad.prism", "--format=github");
  assert.match(github.err, /^::error file=bad\.prism,line=2,col=5,title=prism-verse P012::unknown type `Nope`/);
});

test("explain prints every code of the catalog", () => {
  for (const code of Object.keys(CODES)) assert.equal(cli("explain", code).code, 0);
  assert.match(cli("explain", "p103").out, /^P103: A persisted default changed\.\n\nFix: Keep the old default/);
  assert.equal(cli("explain", "P999").code, 2);
});

test("schema errors exit with 1 and unknown commands with 2", () => {
  assert.equal(cli("check", "bad.prism").code, 1);
  assert.equal(cli("frobnicate").code, 2);
});
