export interface CodeInfo {
  title: string;
  fix?: string;
}

// The catalog behind `prism-verse explain`; docs/errors.md lists the same codes (checked by the tests).
export const CODES: Record<string, CodeInfo> = {
  P001: { title: "Unexpected character." },
  P002: { title: "Unexpected token: the message says what was expected." },
  P003: { title: "Unterminated string.", fix: 'Close the string with `"` on the same line.' },
  P004: { title: "Unknown block.", fix: "A schema holds `datasource`, `generator`, `model`, `type` and `enum` blocks." },
  P005: { title: "Unknown setting in `datasource` or `generator`." },
  P006: { title: "Invalid setting value." },
  P010: { title: "Two declarations share a name." },
  P011: { title: "Two fields of one block share a name." },
  P012: { title: "Unknown type.", fix: "Types are `Int`, `Float`, `Bool`, `String`, or the name of an enum or a type of the schema." },
  P013: { title: "Unknown attribute." },
  P014: { title: "Attribute not allowed here." },
  P015: { title: "Invalid attribute argument." },
  P016: { title: "Attribute given twice." },
  P017: { title: "The default value doesn't match the field type." },
  P018: { title: "Conflicting attributes." },
  P019: { title: "Two fields are saved under one name, or two records share a class name." },
  P020: { title: "Invalid `@version` field.", fix: "Add `Version Int = 1 @version` to a model that has `@@migrate` steps." },
  P021: { title: "Invalid `@lastSeen`, `@firstSeen` or `@saveCount` field." },
  P022: { title: "Invalid `@id` field." },
  P023: { title: "Invalid `@counter`.", fix: "`@counter(List.Field)` names a list of the model and the `@id` field of its type." },
  P024: { title: "Invalid migration step.", fix: "Steps start at 2 and are unique." },
  P025: { title: "More than 4 persistent stores.", fix: "UEFN allows 4 persistent maps per island: merge models." },
  P026: { title: "A type contains itself." },
  P027: { title: "Invalid enum." },
  P028: { title: "Invalid identifier, Verse reserved word, or clash with a generated name." },
  P029: { title: "Nested containers are not supported.", fix: "Wrap the inner level in a `type`." },
  P030: { title: "A model is used as a field type.", fix: "Models are roots: declare the embedded data as a `type`." },
  P031: { title: "`@min` is greater than `@max`." },
  P032: { title: "The `@valid` fallback doesn't match the item type." },
  P033: { title: "A name of the schema is also a Verse module of the project.", fix: "Verse reserves module (folder) names in the whole package: rename the field." },
  P040: { title: "The record can exceed the 256 KB player map limit.", fix: "Lower `@maxItems`, or split the data across two models." },
  P041: { title: "A list has no `@maxItems`.", fix: "Cap it with `@maxItems`, or mark it `@trim(head)` when old items can be dropped." },
  P042: { title: "A list of a model is saved as objects (about 200 bytes of metadata per item).", fix: "Keep the fields of the type flat (no list, option or type) to save it in columns, or add `@@rows` to keep objects." },
  P043: { title: "`@@rows` keeps objects for a type that could be saved in columns.", fix: "Remove `@@rows` unless saves in this format are already published." },
  P101: { title: "A persisted field was removed, renamed with `@map`, or made `@transient`.", fix: "Put it back with `@deprecated`, or restore its `@map` name." },
  P102: { title: "A persisted field changed type.", fix: "Keep the old field (`@deprecated`), add a new one, and convert it in a `@@migrate` step." },
  P103: { title: "A persisted default changed.", fix: "Keep the old default; give new players another value with `@initial`." },
  P104: { title: "A record class was renamed or a type removed.", fix: "Restore the class name with `@@map`." },
  P105: { title: "An enum value was removed or renamed.", fix: "Keep it; add new values after the existing ones." },
  P106: { title: "A store variable was renamed or a model removed.", fix: "Restore it with `@@store`." },
  P107: { title: "`datasource.kind` changed.", fix: "Switching between memory and player is a new store, not an edit." },
  P108: { title: "The version went down.", fix: "Keep every `@@migrate` step." },
  P109: { title: "A published shape can't be read, comes from a newer Prism, or was edited.", fix: "Restore it from version control." },
  P110: { title: "A published migration step was changed or removed.", fix: "Keep published steps as they are; add a new step for a new conversion." },
  P201: { title: "A record class of the schema is not in the Verse files." },
  P202: { title: "A persisted field is missing from the Verse class." },
  P203: { title: "A field type differs." },
  P204: { title: "A field default differs." },
  P205: { title: "The Verse class has a field the schema doesn't declare." },
  P206: { title: "The store variable is missing or has another type." },
  P301: { title: "No persistable class could be parsed." },
  P302: { title: "A field type has no schema equivalent." },
  P901: { title: "File not found." },
  P902: { title: "Output file can't be written." },
};
